baseURL = 'http://willschenk.com/'
languageCode = 'en-us'
title = 'Will Schenk'
theme = 'beard'

[markup.highlight]
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  style = "tango"

[markup.goldmark.renderer]
  unsafe = true

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[[menus.main]]
name = 'Writing'
pageRef = '/writing'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.footer]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.footer]]
name = 'Github'
url = 'https://github.com/wschenk'
weight = 20

[[menus.footer]]
name = 'Mastodon'
url = 'https://floss.social/@wschenk'
weight = 30
