baseURL = "https://willschenk.com/"
relativeURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "en-us"
title = "Will Schenk"
theme="bootstrap"
googleAnalytics = "UA-56296045-1"

[author]
  name = "Will Schenk"

[Social]
  twitter = "wschenk"
  instagram = "wschenk"
  github = "wschenk"
  facebook = "will.schenk"
  linkedin = "will-schenk-420266"

[params]
  description="My home on the internet"

  # [[menu.main]]
  #   name = "About"
  #   weight = 1
  #   identifier = "about"
  #   url = "/about"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

  [[menu.main]]
    name = "Articles"
    weight = 2
  	identifier = "articles"
    url = "/articles/"

[outputFormats]
  [outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"
